export const HOMEPAGE = '/homepage'
export const USER_ENTRY = '/userentry'
export const TRANSCRIPT = '/transcript'
export const CONTEST = '/contest'
export const UNAUTHORIZED = '/unauthorized'
export const RESOURCES = '/resources'
export const PROFILE = '/profile'
export const USERS = '/users'
